/**********************/
/* RoIS_Move.idl  */
/**********************/

#ifndef _ROIS_MOVE_IDL_
#define _ROIS_MOVE_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Move
{
  typedef RoIS_HRI::Integer Integer;
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef sequence<Integer> IntegerSeq;
  
  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in IntegerSeq line,
		in IntegerSeq curve,
		in Integer time
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out IntegerSeq line,
		out IntegerSeq curve,
		out Integer time
	);
  };

  interface Event : RoIS_Common::Event{
  };
};

#endif // _ROIS_MOVE_IDL_
