/****************************************/
/* RoIS_Gesture_Recognition.idl  */
/****************************************/

#ifndef _ROIS_GESTURE_RECOGNITION_IDL_
#define _ROIS_GESTURE_RECOGNITION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Gesture_Recognition
{
  typedef RoIS_HRI::RoIS_IdentifierList RoIS_IdentifierList;
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::DateTime DateTime;

  interface Command : RoIS_Common::Command{
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out RoIS_IdentifierList recognizable_gestures
	);
  };

  interface Event : RoIS_Common::Event{
	void gesture_recognized(
		in DateTime timestamp,
		in RoIS_IdentifierList gesture_ref
	);
  };
};

#endif // _ROIS_GESTURE_RECOGNITION_IDL_
