/*************************************/
/* RoIS_Speech_Synthesis.idl  */
/*************************************/

#ifndef _ROIS_SPEECH_SYNTHESIS_IDL_
#define _ROIS_SPEECH_SYNTHESIS_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Speech_Synthesis
{
  typedef RoIS_HRI::Integer Integer;
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::RoIS_Identifier RoIS_Identifier;
  typedef RoIS_HRI::RoIS_IdentifierList RoIS_IdentifierList;

  typedef sequence<string> StringSeq;

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in string speech_text,
		in string SSML_text,
		in Integer volume,
		in string language,
		in RoIS_Identifier character
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out string speech_text,
		out string SSML_text,
		out Integer volume,
		out string language,
		out RoIS_Identifier character,
		out StringSeq synthesizable_languages,
		out RoIS_IdentifierList synthesizable_characters
	);
  };

  interface Event : RoIS_Common::Event{
  };
};

#endif // _ROIS_SPEECH_SYNTHESIS_IDL_
