/****************************/
/* RoIS_Navigation.idl  */
/****************************/

#ifndef _ROIS_NAVIGATION_IDL_
#define _ROIS_NAVIGATION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Navigation
{
  typedef RoIS_HRI::Integer Integer;
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef sequence<RoLo::Architecture::Data> RoLo_DataSeq;

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in RoLo_DataSeq target_position,
		in Integer time_limit,
		in string routing_policy
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out RoLo_DataSeq target_position,
		out Integer time_limit,
		out string routing_policy
	);
  };

  interface Event : RoIS_Common::Event{
  };
};

#endif // _ROIS_NAVIGATION_IDL_
