/**************************/
/* RoIS_Reaction.idl  */
/**************************/

#ifndef _ROIS_REACTION_IDL_
#define _ROIS_REACTION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Reaction
{
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::RoIS_Identifier RoIS_Identifier;
  typedef RoIS_HRI::RoIS_IdentifierList RoIS_IdentifierList;

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in RoIS_IdentifierList reaction_ref
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out RoIS_IdentifierList available_reactions,
		out RoIS_Identifier reaction_ref
	);
  };

  interface Event : RoIS_Common::Event{
  };
};

#endif // _ROIS_REACTION_IDL_
