/***********************/
/* RoIS_Follow.idl  */
/***********************/

#ifndef _ROIS_FOLLOW_IDL_
#define _ROIS_FOLLOW_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Follow
{
  typedef RoIS_HRI::Integer Integer;
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::RoIS_Identifier RoIS_Identifier;

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in RoIS_Identifier target_object_ref,
		in Integer distance,
		in Integer time_limit
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out RoIS_Identifier target_object_ref,
		out Integer distance,
		out Integer time_limit
	);
  };
};

#endif // _ROIS_FOLLOW_IDL_
