/***************************************/
/* RoIS_Speech_Recognition.idl  */
/***************************************/

#ifndef _ROIS_SPEECH_RECOGNITION_IDL_
#define _ROIS_SPEECH_RECOGNITION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Speech_Recognition
{
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::DateTime DateTime;

  typedef sequence<string> StringSeq;

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in StringSeq languages,
		in string grammer,
		in string rule
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out StringSeq recognizable_languages,
		out StringSeq languages,
		out string grammer,
		out string rule
	);
  };

  interface Event : RoIS_Common::Event{
	void speech_recognized(
		in DateTime timestamp,
		in StringSeq recognized_text
	);
	void speech_input_started(
		in DateTime timestamp
	);
	void speech_input_finished(
		in DateTime timestamp
	);
  };
};

#endif // _ROIS_SPEECH_RECOGNITION_IDL_
