/***************************************/
/* RoIS_Person_Localization.idl  */
/***************************************/

#ifndef _ROIS_PERSON_LOCALIZATION_IDL_
#define _ROIS_PERSON_LOCALIZATION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Person_Localization
{
  typedef RoIS_HRI::Integer Integer;
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::DateTime DateTime;
  typedef RoIS_HRI::RoIS_IdentifierList RoIS_IdentifierList;

  typedef sequence<RoLo::Architecture::Data> RoLo_DataSeq;

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in Integer detection_threshold,
		in Integer minimum_interval
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out Integer detection_threshold,
		out Integer minimum_interval
	);
  };

  interface Event : RoIS_Common::Event{
	void person_localized(
		in DateTime timestamp,
		in RoIS_IdentifierList person_ref,
		in RoLo_DataSeq position_data
	);
  };
};

#endif // _ROIS_PERSON_LOCALIZATION_IDL_
