/**************************************************/
/* RoIS_Service.idl (for Service Application) */
/**************************************************/

#ifndef _ROIS_SERVICE_IDL_
#define _ROIS_SERVICE_IDL_

#pragma prefix "org.omg"

#include "RoIS_HRI.idl"

module RoIS_Service
{
  typedef RoIS_HRI::DateTime DateTime;

  enum Completed_Status
  {
	OK,
	ERROR,
	ABORT,
	OUT_OF_RESOURCES,
	TIMEOUT
  };

  enum ErrorType
  {
	ENGINE_INTERNAL_ERROR,
	COMPONENT_INTERNAL_ERROR,
	COMPONENT_NOT_RESPONDING,
	USER_DEFINED_ERROR
  };

  /* For Service Application Interface */
  interface ServiceApplicationBase{
	void notify_error(
		in string error_id,
		in ErrorType error_type
	);
	void completed(
		in string command_id,
		in Completed_Status status
	);
	void notify_event(
		in string event_id,
		in string event_type,
		in string subscribe_id,
		in DateTime expire
	);
  };
};

#endif // _ROIS_SERVICE_IDL_
