/***************************************/
/* RoIS_System_Information.idl  */
/***************************************/

#ifndef _ROIS_SYSTEM_INFORMATION_IDL_
#define _ROIS_SYSTEM_INFORMATION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module System_Information{
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::DateTime DateTime;
  typedef RoIS_HRI::RoIS_IdentifierList RoIS_IdentifierList;

  typedef RoIS_Common::Component_Status_t Component_Status_t;
  
  typedef sequence<DateTime> DateTimeSeq;
  typedef sequence<RoLo::Architecture::Data> RoLo_DataSeq;

  interface Query : RoIS_Common::Query{
    ReturnCode_t robot_position(
		out DateTime timestamp,
		out RoIS_IdentifierList robot_ref,
		out RoLo_DataSeq position_data
    );
    ReturnCode_t engine_status(
		out Component_Status_t status,
		out DateTimeSeq operable_time
    );
  };
};

#endif // _ROIS_SYSTEM_INFORMATION_IDL_
