/************************/
/* RoIS_Common.idl */
/************************/

#ifndef _ROIS_COMMON_IDL_
#define _ROIS_COMMON_IDL_

#pragma prefix "org.omg"

#include "RoIS_HRI.idl"

module RoIS_Common{
  enum Component_Status
  {
	UNINITIALIZED,
	READY,
	BUSY,
	WARNING,
	ERROR
  };
  typedef long Component_Status_t;

  enum Stream_Status
  {
        STREAMING_NOT_CONNECTED,
        STREAMING_NOT_RUNNING,
        STREAMING_RUNNING,
        STREAMING_SUSPENDED,
        STREAMING_RESUMED,
  };
  typedef long Stream_Status_t;

  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;

  interface Command{
    ReturnCode_t start();
	ReturnCode_t stop();
	ReturnCode_t suspend();
	ReturnCode_t resume();
  };

  interface Query{
	ReturnCode_t component_status(
		out Component_Status_t status
	);
  };

  interface Event{
  };
};

#endif // _ROIS_COMMON_IDL_
