/****************************************/
/* RoIS_Person_Identification.idl  */
/****************************************/

#ifndef _ROIS_PERSON_IDENTIFICATION_IDL_
#define _ROIS_PERSON_IDENTIFICATION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Person_Identification
{
  typedef RoIS_HRI::DateTime DateTime;
  typedef RoIS_HRI::RoIS_IdentifierList RoIS_IdentifierList;

  interface Command : RoIS_Common::Command{
  };

  interface Query : RoIS_Common::Query{
  };

  interface Event : RoIS_Common::Event{
	void person_identified(
		in DateTime timestamp,
		in RoIS_IdentifierList person_ref
	);
  };
};

#endif // _ROIS_PERSON_IDENTIFICATION_IDL_
