/***************************************/
/* RoIS_Audio_Streaming.idl  */
/***************************************/

#ifndef _ROIS_AUDIO_STREAMING_IDL_
#define _ROIS_AUDIO_STREAMING_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Audio_Streaming
{
  typedef RoIS_HRI::ReturnCode_t ReturnCode_t;
  typedef RoIS_HRI::DateTime DateTime;
  typedef RoIS_Common::Stream_Status_t Steram_Status_t;
  

  interface Command : RoIS_Common::Command{
	ReturnCode_t set_parameter(
		in string encoding_parameters,
		in string transport_parameters
	);
	ReturnCode_t connect_stream(
	        out string stream_id
	);
	ReturnCode_t disconnect_stream(
	        out string stream_id
	);
	ReturnCode_t suspend_stream(
	        out string stream_id
	);
	ReturnCode_t resume_stream(
	        out string stream_id
	);
  };

  interface Query : RoIS_Common::Query{
	ReturnCode_t get_parameter(
		out string available_encodings,
		out string available_transports
	);
	ReturnCode_t get_stream_status(
		in string stream_id,
		out Stream_Status statuss
	);
  };

  interface Event : RoIS_Common::Event{
	void notify_stream_status(
		in string stream_id,
		in DateTime timestamp,
		in Stream_Status status
	);
  };
};

#endif // _ROIS_AUDIO_STREAMING_IDL_
