/***********************************/
/* RoIS_Sound_Detection.idl  */
/***********************************/

#ifndef _ROIS_SOUND_DETECTION_IDL_
#define _ROIS_SOUND_DETECTION_IDL_

#pragma prefix "org.omg"

#include "RoIS_Common.idl"

module Sound_Detection
{
  typedef RoIS_HRI::Integer Integer;
  typedef RoIS_HRI::DateTime DateTime;

  interface Command : RoIS_Common::Command{
  };

  interface Query : RoIS_Common::Query{
  };

  interface Event : RoIS_Common::Event{
	void sound_detected(
		in DateTime timestamp,
		in Integer number
	);
  };
};

#endif // _ROIS_SOUND_DETECTION_IDL_
