/*************************************/
/* RoIS_HRI.idl (for HRI Engine) */
/*************************************/

#ifndef _ROIS_HRI_IDL_
#define _ROIS_HRI_IDL_

#pragma prefix "org.omg"

module RoIS_HRI
{
  enum ReturnCode_t
  {
	OK,
	ERROR,
	BAD_PARAMETER,
	UNSUPPORTED,
	OUT_OF_RESOURCES,
	TIMEOUT
  };
  typedef string RoIS_Identifier;
  typedef sequence<RoIS_Identifier> RoIS_IdentifierList;
  typedef string Condition_t;
  typedef string HRI_Engine_Profile;
  typedef string CommandUnitSequence;
  typedef string DateTime;
  typedef long Integer;
  
  struct Result {
	string name;
	RoIS_Identifier data_type_ref;
	any value;
  };

  struct Parameter {
	string name;
	RoIS_Identifier data_type_ref;
	any value;
  };

  struct Argument {
	string name;
	RoIS_Identifier data_type_ref;
	any value;
  };
  
  typedef sequence<Result> ResultList;
  typedef sequence<Parameter> ParameterList;
  typedef sequence<Argument> ArgumentList;

  /* For System Interface */
  interface SystemIF{
	ReturnCode_t connect();
	ReturnCode_t disconnect();
	ReturnCode_t get_profile(
		in Condition_t condition,
		out HRI_Engine_Profile profile
	);
	ReturnCode_t get_error_detail(
		in string error_id,
		in Condition_t condition,
		out ResultList results
	);
  };

  /* For Command Interface */
  interface CommandIF{
	ReturnCode_t search(
		in Condition_t condition,
		out RoIS_IdentifierList component_ref_list
	);
	ReturnCode_t bind(
		in RoIS_Identifier component_ref
	);
	ReturnCode_t bind_any(
		in Condition_t condition,
		out RoIS_Identifier component_ref
	);
	ReturnCode_t release(
		in RoIS_Identifier component_ref
	);
	ReturnCode_t get_parameter(
		in RoIS_Identifier component_ref,
		out ParameterList parameters
	);
	ReturnCode_t set_parameter(
		in RoIS_Identifier component_ref,
		in ParameterList parameters,
		out string command_id
	);
	ReturnCode_t execute(
		in CommandUnitSequence command_unit_list
	);
	ReturnCode_t get_command_result(
		in string command_id,
		in Condition_t condition,
		out ResultList results
	);
  };

  /* For Query Interface */
  interface QueryIF{
	ReturnCode_t query(
		in string query_type,
		in Condition_t condition,
		out ResultList results
	);
};

  /* For Event Interface */
  interface EventIF{
	ReturnCode_t subscribe(
		in string event_type,
		in Condition_t condition,
		out string subscribe_id
	);
	ReturnCode_t unsubscribe(
		in string subscribe_id
	);
	ReturnCode_t get_event_detail(
		in string event_id,
		in Condition_t condition,
		out ResultList results
	);
  };
};

/* RLS related element defined here. */
/* see also: http://www.omg.org/spec/RLS/20110501/Architecture.hpp */

module RoLo {
  module Architecture {
    typedef string Data;
  };
};

#endif // _ROIS_HRI_IDL_
