"""OpenRoIS Interfaces: Transport-independent RoIS type definitions.

This package contains Pydantic models derived from the OMG RoIS Framework
Version 2.0 IDL specification. They are the single source of truth for
all OpenRoIS types, exported to JSON Schema and generated into C# and
TypeScript.

Modules:
    hri:        Core HRI types (ReturnCode, Result, Parameter, Argument, etc.)
    common:     Common component types (ComponentStatus, StreamStatus)
    service:    Service application callback types (CompletedStatus, ErrorType)
    profiles:   Component profile schema models (from XML-Profiles.xsd)
    contract:   ComponentContract protocol and its request, response and event models
    catalog:    Service-side method catalog: params and result models, interfaces
    condition:  The CQL2-Text subset of every condition: parsing, matching, building
    components: Per-component typed message models
"""

from openrois.interfaces.catalog import (
    METHODS,
    METHODS_BY_NAME,
    STREAMING_METHOD_PREFIX,
    BindAnyParams,
    BindAnyResult,
    BindParams,
    BindResult,
    CommandIF,
    ConnectParams,
    ConnectResult,
    DisconnectParams,
    DisconnectResult,
    EventIF,
    ExecuteParams,
    ExecuteResult,
    GetCommandResultParams,
    GetCommandResultResult,
    GetErrorDetailParams,
    GetErrorDetailResult,
    GetEventDetailParams,
    GetEventDetailResult,
    GetParameterParams,
    GetParameterResult,
    GetProfileParams,
    GetProfileResult,
    JsonRpcErrorCode,
    MethodSpec,
    QueryIF,
    QueryParams,
    QueryResult,
    ReleaseParams,
    ReleaseResult,
    SearchParams,
    SearchResult,
    SetParameterParams,
    SetParameterResult,
    SubscribeParams,
    SubscribeResult,
    SystemIF,
    UnsubscribeParams,
    UnsubscribeResult,
)
from openrois.interfaces.common import (
    ComponentStatus,
    ComponentStatusT,
    StreamStatus,
    StreamStatusT,
)
from openrois.interfaces.condition import (
    COMPONENT_REF,
    COMPONENT_TYPE,
    SELECTION_PROPERTIES,
    Comparison,
    Condition,
    ConditionError,
    component_type_urn,
    parse_condition,
)
from openrois.interfaces.contract import (
    CommandRequest,
    ComponentContract,
    ComponentContractError,
    ComponentNotFoundError,
    DiscoverRequest,
    DiscoverResponse,
    EventEnvelope,
    EventSink,
    InvokeResponse,
    QueryRequest,
    QueryResponse,
    SubscribeRequest,
    SubscribeResponse,
)
from openrois.interfaces.hri import (
    Argument,
    ArgumentList,
    CommandId,
    CommandType,
    CommandUnit,
    CommandUnitSequence,
    CommandUnitSequenceItem,
    ConcurrentCommands,
    ConditionT,
    DateTime,
    EventType,
    HRIEngineProfile,
    Integer,
    Parameter,
    ParameterList,
    QueryType,
    Result,
    ResultList,
    ReturnCode,
    RoISIdentifier,
    RoISIdentifierList,
    SubscribeId,
)
from openrois.interfaces.profiles import (
    CommandMessageProfile,
    EventMessageProfile,
    HRIComponentProfile,
    HRIEngineProfileType,
    MessageProfile,
    ParameterProfile,
    QueryMessageProfile,
    RoISIdentifierType,
)
from openrois.interfaces.service import (
    CompletedEvent,
    CompletedStatus,
    ErrorType,
    NotifyErrorEvent,
    NotifyEventPayload,
)

__all__ = [
    # HRI core
    "Argument",
    "ArgumentList",
    "CommandUnit",
    "CommandUnitSequence",
    "CommandUnitSequenceItem",
    "ConcurrentCommands",
    "ConditionT",
    "DateTime",
    "HRIEngineProfile",
    "Integer",
    "Parameter",
    "ParameterList",
    "Result",
    "ResultList",
    "ReturnCode",
    "RoISIdentifier",
    "RoISIdentifierList",
    # Common
    "ComponentStatus",
    "ComponentStatusT",
    "StreamStatus",
    "StreamStatusT",
    # Profiles
    "CommandMessageProfile",
    "EventMessageProfile",
    "HRIComponentProfile",
    "HRIEngineProfileType",
    "MessageProfile",
    "ParameterProfile",
    "QueryMessageProfile",
    "RoISIdentifierType",
    # Service
    "CompletedEvent",
    "CompletedStatus",
    "ErrorType",
    "NotifyErrorEvent",
    "NotifyEventPayload",
    # Method catalog
    "BindAnyParams",
    "BindAnyResult",
    "BindParams",
    "BindResult",
    "CommandIF",
    "ConnectParams",
    "ConnectResult",
    "DisconnectParams",
    "DisconnectResult",
    "EventIF",
    "ExecuteParams",
    "ExecuteResult",
    "GetCommandResultParams",
    "GetCommandResultResult",
    "GetErrorDetailParams",
    "GetErrorDetailResult",
    "GetEventDetailParams",
    "GetEventDetailResult",
    "GetParameterParams",
    "GetParameterResult",
    "GetProfileParams",
    "GetProfileResult",
    "JsonRpcErrorCode",
    "METHODS",
    "METHODS_BY_NAME",
    "MethodSpec",
    "QueryIF",
    "QueryParams",
    "QueryResult",
    "ReleaseParams",
    "ReleaseResult",
    "STREAMING_METHOD_PREFIX",
    "SearchParams",
    "SearchResult",
    "SetParameterParams",
    "SetParameterResult",
    "SubscribeParams",
    "SubscribeResult",
    "SystemIF",
    "UnsubscribeParams",
    "UnsubscribeResult",
    # Conditions
    "COMPONENT_REF",
    "COMPONENT_TYPE",
    "SELECTION_PROPERTIES",
    "Comparison",
    "Condition",
    "ConditionError",
    "component_type_urn",
    "parse_condition",
    # Component Contract
    "ComponentContractError",
    "CommandId",
    "CommandRequest",
    "CommandType",
    "ComponentContract",
    "ComponentNotFoundError",
    "DiscoverRequest",
    "DiscoverResponse",
    "EventEnvelope",
    "EventSink",
    "EventType",
    "InvokeResponse",
    "QueryRequest",
    "QueryResponse",
    "QueryType",
    "SubscribeId",
    "SubscribeRequest",
    "SubscribeResponse",
]
